Documentation:
  Enabled: false

LineLength:
  Max: 120

NumericLiterals:
  Enabled: false

TrivialAccessors:
  Enabled: false

SpecialGlobalVars:
  Enabled: false

MethodLength:
  Enabled: false

HandleExceptions:
  Enabled: false

PredicateName:
  Enabled: false

ClassLength:
  Max: 130

ParameterLists:
  Max: 7

Style/TrailingComma:
  Enabled: false

RedundantSelf:
  Enabled: false

Style/SignalException:
  EnforcedStyle: only_raise
