---
resources:
  - name: prof
    type: git
    source:
      uri: https://github.com/pivotal-cf-experimental/prof
      branch: master

  - name: time-24hours
    type: time
    source:
      interval: 24h

  - name: alert
    type: slack-notification
    source:
      url: https://hooks.slack.com/services/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

jobs:
  - name: tests
    plan:
    - do:
      - aggregate:
        - get: prof
          trigger: true
        - get: time-24hours
          trigger: true
      - task: run-tests
        file: prof/ci/run-tests.yml
    - put: alert
      params:
        text: "Sorry, I don't know how to tell you this, but 'prof' pipeline is broken."
        channel: "#london-services"
        username: concourse
        icon_url: http://cl.ly/image/3e1h0H3H2s0P/concourse-logo.png
