---
resources:
  - name: prof
    type: git
    source:
      uri: https://github.com/pivotal-cf-experimental/prof
      branch: master

  - name: time-24hours
    type: time
    source:
      interval: 24h

jobs:
  - name: tests
    plan:
    - do:
      - aggregate:
        - get: prof
          trigger: true
        - get: time-24hours
          trigger: true
      - task: run-tests
        file: prof/ci/run-tests.yml
